### ISSUE TITLE
Where to put cleanup (dispose code)

### ISSUE THREAD

**Issue by danielscherzer** [varon/GLWpfControl#32]
Thansk for a great control!
When I want to dispose GL resources, like textures or frame buffers when the control is no longer used, I found only the Unloaded event provided by WPF. But this event is not called on application shutdown (https://docs.microsoft.com/en-us/dotnet/api/system.windows.frameworkelement.unloaded?view=net-5.0).
I opted for `Dispatcher.ShutdownStarted` but this will only be called on application shutdown and not on other visual changes, which may require disposal and recreation of resources. Of course I could handle both, but this seems hackish to me.

What is your best practice in this case?

One suggestion in the thread
https://stackoverflow.com/questions/1550212/proper-cleanup-of-wpf-user-controls is to override the `OnVisualParentChanged`.

**Comment by varon** [comment]
If you close the process all resources are freed automatically. Don't worry about GL stuff in the case of a full application shutdown.

**Comment by danielscherzer** [comment]
Thanks for your feedback!

**Comment by romen-h** [comment]
I have the same question. I am wondering where the right place is to call my cleanup code for closing a child form with a GLWpfControl. The application is not shutting down, and multiple forms can be opened and closed so cleanup must be performed successfully.

The problem I am having now is that it seems like the WPF parent control is being garbage collected while my cleanup code is executing. Although I am not doing it asynchronously. Right now calling my cleanup in Window.Closing.

**Comment by anose001** [comment]
@romen-h, have you been able to clean up all your GL resources, including the GLWpfControl properly? I also ran into a AccessViolationException in my project. Any help is greatly appreciated
