### ISSUE TITLE
Quick Font Support?

### ISSUE THREAD

**Issue by mostafa901** [varon/GLWpfControl#6]
does this support Quickfont Library? I tried to implement QuickFont but it rendered nothing :(... 
a quick repocode for this:
[repo](https://github.com/mostafa901/OpenGL_CSharp/blob/test_QuickFont/OpenGL_Wpf/MainWindow.xaml.cs)

**Comment by varon** [comment]
This should be Standard OpenGL. Anything compatible should work.

As for text rendering, typically I'd advise just using a normal WPF label over the top if you can.

3D text is always a bit rough to get right.
