### ISSUE TITLE
Blurred texture wpf control Width issue.

### ISSUE THREAD

**Issue by solidcore-commodore** [varon/GLWpfControl#7]
I am new to opentk so please forgive me,

I started a new WPF project and with the help of justin113d and lots of confusion later I was finally able to render to the wpf control.

However soon after I noticed that my 100x100 pixel image that I rendered as a texture to two triangles was blurry, I then noticed the edges of the wpf control had white lines down the side of it.

The control is 800x800 and the viewport is 800x800. 

Taking a screenshot of the wpf control under the advice of jvbsl I was able to measure the control as 801x800, so resizing the control to 799x800 resolved my pixel blurred issues not only on the lines left+right of the wpf control but the rendered triangle texture as well.

Please let me know if you need further details.

**Comment by varon** [comment]
Totally missed this. Looks like a rounding issue at certain sizes. If you can figure it out, we'd love a PR.

The code is super super simple.

**Comment by varon** [comment]
Should be fixed as part of 3.0.0
